name: 'check-branches'
on: 
  pull_request:
    branches: 
      - 'prod*'
    types: [synchronize, opened, reopened, edited, closed]

jobs:
  tag-for-report:
    if: github.event.pull_request.merged == true
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Using action'
        uses: './'
